const translations = {
    en : {
        calculatorTitle: 'Loan Calculator',
        amountLabel: 'Amount',
        amountHelpText: 'This is the total amount you wish to borrow.',
        monthlyDepositLabel: 'Monthly Deposit',
        balance: 'Balance',
        interest: 'Interest',
        totalPrincipalPaid: 'Total Principal Paid',
        totalInterestPaid: 'Total Interest Paid',
        principalPaid: 'Principal paid',
        interestPaid: 'Interest paid',
        monthYearText: 'Month/Year',
        interestHelpText: 'This is the annual interest rate of your loan; it’s should be defined in your loan agreement.',
        payments: 'Payments',
        paymentSingular: 'Payment',
        paymentLower: 'payments',
        monthlyPayments: 'Monthly Payments',
        interestLabel: 'Interest rate',
        monthly: 'monthly',
        yearText: 'year',
        yearPluralText: 'years',
        yearPluralTextCaipal: 'Years',
        TimeToRepayText: 'Time to repay',
        totalBalanceText: 'Total balance',
        totalInterestText: 'Total interest',
        monthlyText: 'Monthly',
        anuallyText: 'Anually',
        biweeklyText: "Bi-weekly",
        biweeklyLowerText: "bi-weekly",
        loanAmount: 'Loan Amount',
        termInYears: 'Loan term in years',
        termInMonths: 'or months',
        orText: 'Or',
        dateHelpText: 'The term of a loan is the amount of time you have to pay it off in full. Please choose a term in either years or months.',
        startDateText: 'Start Date',
        startDateHelpText: 'This is the date you will receive your funds. Payments usually begin the month after the start date.',
        moneyFieldError: 'Use positive numbers less than 1 million.',
        percentageFieldError: 'Use positive numbers less than 100.',
        yearsError: 'Use real number of years (Less than 100).',
        monthsError: 'Use real number of months (Less than 1200).',
        timeError: 'Use real number of years and months (1 < years < 100 | 12 < months < 1200).',
        estimatedPayoffDate: 'Estimated Payoff Date',
        amortizationSchedule: 'Amortization Schedule',
        startingDateEmptyText: 'There is no starting date selected.',
        selectDatePlaceholder: 'Click to select a date',
        fullMonths: ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'],
        shortMonths: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'],
        showAmortizationBtnText: 'Show Amortization Schedule',
        hideAmortizationBtnText: 'Hide Amortization Schedule',
        withExtraPayments: 'With extra payments',
        withoutExtraPayments: 'Without extra payments',
        showExtraPayments: 'Add Extra Payments',
        hideExtraPayments: 'Hide Extra Payments',
        extraPaymentsText1: 'Enter an amount on one of the options below and click “Add Extra Payments” to see how it will change the monthly payment, interest paid and total cost of your loan.',
        extraPaymentHelp1: 'Add a set amount of money that you will add to your monthly payment every month.',
        extraPaymentHelp2: 'Make one extra payment every year on a set month.',
        extraPaymentHelp3: 'Make a one-time extra payment on a designated month and year',
        extraPaymentLabel1: 'add to your monthly payment',
        extraPaymentLabel2: 'as an extra annual payment every:',
        extraPaymentLabel3: 'as a one-time extra payment in:',
        addExtraBtnTitle: 'Add Extra Payments',
        extraLumpError: 'Extra payment cannot be made before the current date.',
        dateHelpMessage: '*Please enter a date as: mm/dd/yyyy',
        amortizationTableHelp: 'This table summarizes the repayment schedule of a loan, including dividing the monthly payment between principal and interest charges, total interest paid and the balance of the loan after each payment.',
    },
    es : {
        calculatorTitle: 'Calculadora de Préstamos',
        amountLabel: 'Monto',
        amountHelpText: 'Es la cantidad total que desea tomar prestada.',
        monthlyDepositLabel: 'Depósito Mensual',
        balance: 'Balance',
        interest: 'Interés',
        totalPrincipalPaid: 'Total del monto principal pagado',
        totalInterestPaid: 'Total del interés pagado',
        principalPaid: 'Principal',
        interestPaid: 'Interés pagado',
        monthYearText: 'Mes/Año',
        interestHelpText: 'Es la tasa de interés anual de su préstamo, que debe ser definida en el contrato del préstamo.',
        payments: 'Pagos',
        paymentSingular: 'Pago',
        paymentLower: 'pagos',
        monthlyPayments: 'Pagos mensuales',
        interestLabel: 'Tasa de interés',
        monthly: 'mensual',
        yearText: 'año',
        yearPluralText: 'años',
        yearPluralTextCaipal: 'Años',
        TimeToRepayText: 'Tiempo para pagar',
        totalInterestText: 'Interés total',
        monthlyText: 'Mensual',
        anuallyText: 'Anual',
        biweeklyText: "Quincenal",
        loanAmount: 'Monto del préstamo',
        termInYears: 'Término en años',
        termInMonths: 'o meses',
        orText: 'O',
        dateHelpText: 'El término de un préstamo es la cantidad de tiempo que usted tendrá para pagar el total del monto. Por favor escoja un término en años o meses.',
        startDateText: 'Fecha de Comienzo',
        startDateHelpText: 'Es la fecha en que usted recibirá el dinero prestado. Usualmente los pagos comienzan el mes siguiente luego de la fecha de comienzo.',
        moneyFieldError: 'Use números positivos menores que 1 millón.',
        percentageFieldError: 'Use números positivos menores que 100',
        yearsError: 'Use una cantidad real de años. No se permiten puntos.',
        monthsError: 'Use una cantidad real de meses (menos de 1200).',
        timeError: 'Use un número real de años o meses (años <100 | meses <1200).',
        estimatedPayoffDate: 'Fecha Estimada de su Pago Final',
        amortizationSchedule: 'Plan de amortización',
        startingDateEmptyText: 'No hay una fecha de inicio seleccionada.',
        selectDatePlaceholder: 'Seleccione una fecha',
        fullMonths: ['Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio', 'Julio', 'Agosto', 'Septiembre', 'Octubre', 'Noviembre', 'Diciembre'],
        shortMonths: ['Ene', 'Feb', 'Mar', 'Abr', 'May', 'Jun', 'Jul', 'Ago', 'Sep', 'Oct', 'Nov', 'Dic'],
        showAmortizationBtnText: 'Ver tabla de amortización',
        hideAmortizationBtnText: 'Ocultar tabla de amortización',
        withExtraPayments: 'Con pagos extras',
        withoutExtraPayments: 'Sin pagos extras',
        showExtraPayments: 'Añadir Pagos Adicionales',
        hideExtraPayments: 'Ocultar Pagos Extras',
        extraPaymentsText1: 'Ingrese la cantidad en una de las alternativas abajo, luego haga click en “Añadir Pagos Adicionales” para ver cómo cambia su pago mensual, el interés pagado y el costo total de su préstamo.',
        extraPaymentHelp1: 'Añadir una cantidad de dinero determinada a su pago mensual.',
        extraPaymentHelp2: 'Hacer un pago adicional cada año, en un mes determinado.',
        extraPaymentHelp3: 'Hacer un pago adicional por única vez en un mes y año determinados.',
        extraPaymentLabel1: 'añadir a su pago mensual',
        extraPaymentLabel2: 'como un pago anual extra cada:',
        extraPaymentLabel3: 'como un pago único extra en:',
        addExtraBtnTitle: 'Adicionar pagos extras',
        extraLumpError: 'El pago adicional no puede hacerse antes de la fecha actual.',
        dateHelpMessage: '*Por favor ingrese la fecha en formato mm/dd/año (el año debe tener cuatro dígitos)',
        amortizationTableHelp: 'Esta tabla resume el plan de pagos de un préstamo, incluyendo el desglose del pago mensual entre el balance principal y los cargos por interés, el interés total pagado y el balance del préstamo luego de cada pago.',
    },
    ca : {
        calculatorTitle: 'Loan Calculator',
        amountLabel: 'Amount',
        amountHelpText: 'This is the total amount you wish to borrow.',
        monthlyDepositLabel: 'Monthly Deposit',
        balance: 'Balance',
        interest: 'Interest',
        totalPrincipalPaid: 'Total Principal Paid',
        totalInterestPaid: 'Total Interest Paid',
        principalPaid: 'Principal paid',
        interestPaid: 'Interest paid',
        monthYearText: 'Month/Year',
        interestHelpText: 'This is the annual interest rate of your loan; it’s should be defined in your loan agreement.',
        payments: 'Payments',
        paymentSingular: 'Payment',
        paymentLower: 'payments',
        monthlyPayments: 'Monthly Payments',
        interestLabel: 'Interest rate',
        monthly: 'monthly',
        yearText: 'year',
        yearPluralText: 'years',
        yearPluralTextCaipal: 'Years',
        TimeToRepayText: 'Time to repay',
        totalBalanceText: 'Total balance',
        totalInterestText: 'Total interest',
        monthlyText: 'Monthly',
        anuallyText: 'Anually',
        biweeklyText: "Bi-weekly",
        loanAmount: 'Loan Amount',
        termInYears: 'Loan term in years',
        termInMonths: 'or months',
        orText: 'Or',
        dateHelpText: 'The term of a loan is the amount of time you have to pay it off in full. Please choose a term in either years or months.',
        startDateText: 'Start Date',
        startDateHelpText: 'This is the date you will receive your funds. Payments usually begin the month after the start date.',
        moneyFieldError: 'Use positive numbers less than 1 million.',
        percentageFieldError: 'Use positive numbers less than 100.',
        yearsError: 'Use real number of years (Less than 100).',
        monthsError: 'Use real number of months (Less than 1200).',
        timeError: 'Use real number of years and months (1 < years < 100 | 12 < months < 1200).',
        estimatedPayoffDate: 'Estimated Payoff Date',
        amortizationSchedule: 'Amortization Schedule',
        startingDateEmptyText: 'There is no starting date selected.',
        selectDatePlaceholder: 'Click to select a date',
        fullMonths: ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'],
        shortMonths: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'],
        showAmortizationBtnText: 'Show Amortization Schedule',
        hideAmortizationBtnText: 'Hide Amortization Schedule',
        withExtraPayments: 'With extra payments',
        withoutExtraPayments: 'Without extra payments',
        showExtraPayments: 'Add Extra Payments',
        hideExtraPayments: 'Hide Extra Payments',
        extraPaymentsText1: 'Enter an amount on one of the options below and click “Add Extra Payments” to see how it will change the monthly payment, interest paid and total cost of your loan.',
        extraPaymentHelp1: 'Add a set amount of money that you will add to your monthly payment every month.',
        extraPaymentHelp2: 'Make one extra payment every year on a set month.',
        extraPaymentHelp3: 'Make a one-time extra payment on a designated month and year',
        extraPaymentLabel1: 'add to your monthly payment',
        extraPaymentLabel2: 'as an extra annual payment every:',
        extraPaymentLabel3: 'as a one-time extra payment in:',
        addExtraBtnTitle: 'Add Extra Payments',
        extraLumpError: 'Extra payment cannot be made before the current date.',
        dateHelpMessage: '*Please enter a Date as: mm/dd/yyyy',
        amortizationTableHelp: 'This table summarizes the repayment schedule of a loan, including dividing the monthly payment between principal and interest charges, total interest paid and the balance of the loan after each payment.',
    },
    fr : {
        calculatorTitle: 'Loan Calculator',
        amountLabel: 'Amount',
        amountHelpText: 'This is the total amount you wish to borrow.',
        monthlyDepositLabel: 'Monthly Deposit',
        balance: 'Balance',
        interest: 'Interest',
        totalPrincipalPaid: 'Total Principal Paid',
        totalInterestPaid: 'Total Interest Paid',
        principalPaid: 'Principal paid',
        interestPaid: 'Interest paid',
        monthYearText: 'Month/Year',
        interestHelpText: 'This is the annual interest rate of your loan; it’s should be defined in your loan agreement.',
        payments: 'Payments',
        paymentSingular: 'Payment',
        paymentLower: 'payments',
        monthlyPayments: 'Monthly Payments',
        interestLabel: 'Interest rate',
        monthly: 'monthly',
        yearText: 'year',
        yearPluralText: 'years',
        yearPluralTextCaipal: 'Years',
        TimeToRepayText: 'Time to repay',
        totalBalanceText: 'Total balance',
        totalInterestText: 'Total interest',
        monthlyText: 'Monthly',
        anuallyText: 'Anually',
        biweeklyText: "Bi-weekly",
        loanAmount: 'Loan Amount',
        termInYears: 'Term in years',
        termInMonths: 'or months',
        orText: 'Or',
        dateHelpText: 'The term of a loan is the amount of time you have to pay it off in full. Please choose a term in either years or months.',
        startDateText: 'Start Date',
        startDateHelpText: 'This is the date you will receive your funds. Payments usually begin the month after the start date.',
        moneyFieldError: 'Use positive numbers less than 1 million.',
        percentageFieldError: 'Use positive numbers less than 100.',
        yearsError: 'Use real number of years (Less than 100).',
        monthsError: 'Use real number of months (Less than 1200).',
        timeError: 'Use real number of years and months (1 < years < 100 | 12 < months < 1200).',
        estimatedPayoffDate: 'Estimated Payoff Date',
        amortizationSchedule: 'Amortization Schedule',
        startingDateEmptyText: 'There is no starting date selected.',
        selectDatePlaceholder: 'Click to select a date',
        fullMonths: ['Janvier', 'Février', 'Mars', 'Avril', 'Mai', 'Juin', 'Juillet', 'Août', 'Septembre', 'Octobre', 'Novembre', 'Décembre'],
        shortMonths: ['Jan', 'Fév', 'Mar', 'Avr', 'Mai', 'Jui', 'Juil', 'Aoû', 'Sep', 'Oct', 'Nov', 'Déc'],
        showAmortizationBtnText: 'Show Amortization Schedule',
        hideAmortizationBtnText: 'Hide Amortization Schedule',
        withExtraPayments: 'With extra payments',
        withoutExtraPayments: 'Without extra payments',
        showExtraPayments: 'Add Extra Payments',
        hideExtraPayments: 'Hide Extra Payments',
        extraPaymentsText1: 'Enter an amount on one of the options below and click “Add Extra Payments” to see how it will change the monthly payment, interest paid and total cost of your loan.',
        extraPaymentHelp1: 'Add a set amount of money that you will add to your monthly payment every month.',
        extraPaymentHelp2: 'Make one extra payment every year on a set month.',
        extraPaymentHelp3: 'Make a one-time extra payment on a designated month and year',
        extraPaymentLabel1: 'add to your monthly payment',
        extraPaymentLabel2: 'as an extra annual payment every:',
        extraPaymentLabel3: 'as a one-time extra payment in:',
        addExtraBtnTitle: 'Add Extra Payments',
        extraLumpError: 'Extra payment cannot be made before the current date.',
        dateHelpMessage: '*Please enter a valid Date format (mm/dd/year)',
        amortizationTableHelp: 'This table summarizes the repayment schedule of a loan, including dividing the monthly payment between principal and interest charges, total interest paid and the balance of the loan after each payment.',
    },

};

export default function getTranslations(lan) {
    return translations[lan];
}