const translations = {
    en : {
        grossAnnualIncome: "Gross Annual Income",
        enterAnualIncome: "Enter your Annual Income",
        incomeFieldError: "The number should be greather than 0.",
        percentageBaseonIncome: "Percentage based on your Income",
        slidersRangeNote: "Please note that the sliders will only allow you to move up to the total dollar amount of your budget. In order to move the slider up in one category, you'll need to move another slider down first, so you have funds available to increase your spending.",
        budgetRemaining: "Budget Remaining",
        totalBudget: "Total Budget",
        yourIncome: "Your income",
        budgetBaseOnIncome: "Selected budget based on your income",
        distributionExpensesActivity: "Overview of your budget",
        realMoneyToExpend: "Real money you will spend",
        previous: "Previous",
        next: "Next",
        submit: "Submit & review",
        print: "Print",
    },
    es : {
        grossAnnualIncome: "Ingreso Anual",
        enterAnualIncome: "Introduzca su Ingreso Anual",
        incomeFieldError: "El valor de este campo debe ser mayor que 0.",
        percentageBaseonIncome: "Porcentaje basado en sus ingresos",
        slidersRangeNote: "Por favor, tenga en cuenta que los controles de deslizamiento solo le permitirán subir hasta el monto en dólares de su presupuesto. Para poder hacer un aumento en una categoría, primero deberá bajar otra, de modo que tenga fondos disponibles para aumentar su gasto.",
        budgetRemaining: "Remanente del presupuesto total",
        totalBudget: "Presupuesto Total",
        yourIncome: "Su ingreso anual",
        budgetBaseOnIncome: "Presupuesto seleccionado basado en sus ingresos",
        distributionExpensesActivity: "Distribución de Gastos por Actividad",
        realMoneyToExpend: "Cantidad de dinero real que va a gastar",
        previous: "Anterior",
        next: "Siguiente",
        submit: "Enviar",
        print: "Imprimir",
    },
    ca : {
        grossAnnualIncome: "Gross Annual Income",
        enterAnualIncome: "Enter your Annual Income",
        incomeFieldError: "The number should be greather than 0.",
        percentageBaseonIncome: "Percentage based on your Income",
        slidersRangeNote: "Please note that the sliders will only allow you to move up to the total dollar amount of your budget. In order to move the slider up in one category, you'll need to move another slider down first, so you have funds available to increase your spending.",
        budgetRemaining: "Budget Remaining",
        totalBudget: "Total Budget",
        yourIncome: "Your income",
        budgetBaseOnIncome: "Selected budget based on your income",
        distributionExpensesActivity: "Overview of your budget",
        realMoneyToExpend: "Real money you will spend",
        previous: "Previous",
        next: "Next",
        submit: "Submit & review",
        print: "Print",
    },
    fr : {
        grossAnnualIncome: "Gross Annual Income",
        enterAnualIncome: "Enter your Annual Income",
        incomeFieldError: "The number should be greather than 0.",
        percentageBaseonIncome: "Percentage based on your Income",
        slidersRangeNote: "Please note that the sliders will only allow you to move up to the total dollar amount of your budget. In order to move the slider up in one category, you'll need to move another slider down first, so you have funds available to increase your spending.",
        budgetRemaining: "Budget Remaining",
        totalBudget: "Total Budget",
        yourIncome: "Your income",
        budgetBaseOnIncome: "Selected budget based on your income",
        distributionExpensesActivity: "Overview of your budget",
        realMoneyToExpend: "Real money you will spend",
        previous: "Previous",
        next: "Next",
        submit: "Submit & review",
        print: "Print",
    }

};

export default function getTranslations(lan) {
    return translations[lan];
}