const translations = {
    en : {
        amountLabel: 'Amount',
        monthlyDepositLabel: 'Monthly Deposit',
        balance: 'Balance',
        interest: 'Interest',
        payments: 'Payments',
        paymentSingular: 'Payment',
        paymentLower: 'payments',
        interestLabel: 'Interest rate',
        monthly: 'monthly',
        yearText: 'year',
        yearPluralText: 'years',
        yearPluralTextCaipal: 'Years',
        TimeToRepayText: 'Time to repay',
        totalBalanceText: 'Total balance',
        totalInterestText: 'Total interest',
        monthlyText: 'Monthly',
        anuallyText: 'Anually',
        biweeklyText: "Bi-weekly",
        biweeklyLowerText: "bi-weekly",
        loanAmount: 'Loan Amount',
        termInYears: 'Term in years',
        termInMonths: 'or months',
        orText: 'Or',
        moneyFieldError: 'Use positive numbers less than 1 million.',
        percentageFieldError: 'Use positive numbers less than 100.',
        yearsError: 'Use real number of years (Less than 100).',
        monthsError: 'Use real number of months (Less than 1200).',
        timeError: 'Use real number of years and months (1 < years < 100 | 12 < months < 1200).',
        tableResultsTitle: 'Annual breakdown of payments',
        loadingText: 'Loading...',
    },
    es : {
        amountLabel: 'Monto',
        monthlyDepositLabel: 'Depósito Mensual',
        balance: 'Balance',
        interest: 'Interés',
        payments: 'Pagos',
        paymentSingular: 'Pago',
        paymentLower: 'pagos',
        interestLabel: 'Tasa de interés',
        monthly: 'mensual',
        yearText: 'año',
        yearPluralText: 'años',
        yearPluralTextCaipal: 'Años',
        TimeToRepayText: 'Tiempo para pagar',
        totalInterestText: 'Interés total',
        monthlyText: 'Mensual',
        anuallyText: 'Anual',
        biweeklyText: "Quincenal",
        loanAmount: 'Monto del préstamo',
        termInYears: 'Término en años',
        termInMonths: 'o meses',
        orText: 'O',
        moneyFieldError: 'Use positive numbers less than 1 million.',
        percentageFieldError: 'Use positive numbers less than 100.',
        yearsError: 'Use real number of years. No dots allowed.',
        monthsError: 'Use real number of months (Less than 1200).',
        timeError: 'Use real number of years and months (years < 100 | months < 1200).',
        tableResultsTitle: 'Desglose anual de pagos',
        loadingText: 'Loading...',
    },
    ca : {
        amountLabel: 'Amount',
        monthlyDepositLabel: 'Monthly Deposit',
        balance: 'Balance',
        interest: 'Interest',
        payments: 'Payments',
        paymentSingular: 'Payment',
        paymentLower: 'payments',
        interestLabel: 'Interest rate',
        monthly: 'monthly',
        yearText: 'year',
        yearPluralText: 'years',
        yearPluralTextCaipal: 'Years',
        TimeToRepayText: 'Time to repay',
        totalBalanceText: 'Total balance',
        totalInterestText: 'Total interest',
        monthlyText: 'Monthly',
        anuallyText: 'Anually',
        biweeklyText: "Bi-weekly",
        loanAmount: 'Loan Amount',
        termInYears: 'Term in years',
        termInMonths: 'or months',
        orText: 'Or',
        moneyFieldError: 'Use positive numbers less than 1 million.',
        percentageFieldError: 'Use positive numbers less than 100.',
        yearsError: 'Use real number of years (Less than 100).',
        monthsError: 'Use real number of months (Less than 1200).',
        timeError: 'Use real number of years and months (1 < years < 100 | 12 < months < 1200).',
        tableResultsTitle: 'Annual breakdown of payments',
        loadingText: 'Loading...',
    },
    fr : {
        amountLabel: 'Amount',
        monthlyDepositLabel: 'Monthly Deposit',
        balance: 'Balance',
        interest: 'Interest',
        payments: 'Payments',
        paymentSingular: 'Payment',
        paymentLower: 'payments',
        interestLabel: 'Interest rate',
        monthly: 'monthly',
        yearText: 'year',
        yearPluralText: 'years',
        yearPluralTextCaipal: 'Years',
        TimeToRepayText: 'Time to repay',
        totalBalanceText: 'Total balance',
        totalInterestText: 'Total interest',
        monthlyText: 'Monthly',
        anuallyText: 'Anually',
        biweeklyText: "Bi-weekly",
        loanAmount: 'Loan Amount',
        termInYears: 'Term in years',
        termInMonths: 'or months',
        orText: 'Or',
        moneyFieldError: 'Use positive numbers less than 1 million.',
        percentageFieldError: 'Use positive numbers less than 100.',
        yearsError: 'Use real number of years (Less than 100).',
        monthsError: 'Use real number of months (Less than 1200).',
        timeError: 'Use real number of years and months (1 < years < 100 | 12 < months < 1200).',
        tableResultsTitle: 'Annual breakdown of payments',
        loadingText: 'Loading...',
    },

};

export default function getTranslations(lan) {
    return translations[lan];
}