const translations = {
    en : {
        monthlyIncomeText: "Total Monthly Income",
        monthlyDebtPaymentsText: 'Total Monthly Payments',
        yourMonthlyIncome: "Your Monthly Income",
        partnerMonthlyIncome: "Partner's Monthly Income",
        alimoneyChildSupport: "Alimony / Child Support Received",
        pensionRetirementReceived: "Pension / Retirement Benefits",
        socialSecurityReceived: "Social Security Benefits",
        governmentAssistance: "Government Assistance",
        otherMonthlyIncome : "Other",

        rentMortgage: "Monthly Rent/Mortgage",
        carPayments: "Monthly Car Payments",
        carInsurance: "Monthly Car Insurance",
        privateHealthInsurance: "Private Health Insurance",
        medicalDentalBillPayments: "Medical / Dental Bill Payments",
        alimonyChildSupportPayments: "Alimony / Child Support Payments",
        totalMonthlyCreditCardPayments: "Monthly Credit Card Payments",
        studentLoanPayments: "Student Loan Payments",
        applianceFurniturePayments: "Appliance / Furniture Payments",
        otherLoanPayments: "Other Loan Payments",

        resultsBreakdown: "Here are Your Results…",
        fieldsErrorMessage: 'Your income is lower than your expenses.',
        safeWord: 'Safe',
        okWord: 'OK',
        stressfulWord: 'Too High',
        totalIncomeText: 'Total Income',
        totalDebtText: 'Total Debt',
        debtRatioText: 'Debt Ratio',
        helpText: 'Provide at least one value per section.',
        debtText: 'Debts',
        remainingsText: 'Remaining',
        //chartHelpAText: 'The more remaining you have per month, the more stable your financial situation is.',
        chartHelpAText: 'The less income that you spend on debt, the easier it is to maintain stability. Keeping a low DTI also helps you avoid credit card debt.',
        //chartHelpBText: 'Your Debt to Income Ratio is high, you should contact a Debt Counselor immediately.',
        chartHelpBText: 'Focus on paying off debt until your DTI is below 36%. Avoid applying for loans and making new credit card charges until then.',
        chartHelpCText: 'Spending this much income on debt can make it difficult to balance your budget. You may be relying on credit to cover daily expenses.',
    },
    es : {
        monthlyIncomeText: "Ingreso total mensual",
        monthlyDebtPaymentsText: 'Total de pagos mensuales',
        yourMonthlyIncome: "Su ingreso mensual",
        partnerMonthlyIncome: "Ingreso mensual del otro",
        alimoneyChildSupport: "Pensión Alimenticia / manutención recibida",
        pensionRetirementReceived: "Pensión / Beneficios de Jubilación",
        socialSecurityReceived: "Beneficios del Seguro Social",
        governmentAssistance: "Asistencia Gubernamental",
        otherMonthlyIncome : "Otros",

        rentMortgage: "Renta / Hipoteca",
        carPayments: "Pagos del auto",
        carInsurance: "Seguro de auto",
        privateHealthInsurance: "Seguro de Salud Privado",
        medicalDentalBillPayments: "Pagos de cuentas médicas/dentales",
        alimonyChildSupportPayments: "Pagos de Pensión Alimenticia / manutención de menores",
        totalMonthlyCreditCardPayments: "Total de pagos mensuales de tarjetas de crédito",
        studentLoanPayments: "Pagos de prestamos estudiantiles",
        applianceFurniturePayments: "Pagos de Electrodomésticos / muebles",
        otherLoanPayments: "Otros pagos extras",

        resultsBreakdown: "Aquí están tus resultados",
        fieldsErrorMessage: 'Sus ingresos son más bajos que sus gastos.',
        safeWord: 'A salvo',
        okWord: 'OK',
        stressfulWord: 'Muy Alta',
        totalIncomeText: 'Total de Ingresos',
        totalDebtText: 'Deuda Total Mensual',
        debtRatioText: 'Relación de la Deuda',
        helpText: 'Ingrese al menos un valor por sección',
        debtText: 'Deudas',
        remainingsText: 'Restante',
        //chartHelpAText: 'Cuanto más dinero le quede por mes, mejor será su relación deuda / ingresos.',
        chartHelpAText: 'Cuanto menos ingresos gastes en deudas, más fácil será mantener tu estabilidad financiera. Mantener un DTI (Relación Deuda a Ingreso)  bajo también lo ayuda a evitar deudas de tarjetas de crédito.',
        //chartHelpBText: 'Cuanto más dinero le quede por mes, mejor será su relación deuda / ingresos.',
        chartHelpBText: 'Concéntrate en pagar la deuda hasta que tu relación deuda-ingreso sea inferior al 36%. Evita solicitar préstamos y hacer nuevos cargos en la tarjeta de crédito hasta entonces.',
        chartHelpCText: 'Gastar tantos ingresos en deudas puede dificultar el equilibrio de tu presupuesto. Puedes utilizar tus tarjetas de crédito para cubrir los gastos diarios.',
    },
    ca : {
        monthlyIncomeText: "Total Monthly Income",
        monthlyDebtPaymentsText: 'Total Monthly Payments',
        yourMonthlyIncome: "Your Monthly Income",
        partnerMonthlyIncome: "Partner's Monthly Income",
        alimoneyChildSupport: "Alimony / Child Support Received",
        pensionRetirementReceived: "Pension / Retirement Benefits",
        socialSecurityReceived: "Social Security Benefits",
        governmentAssistance: "Government Assistance",
        otherMonthlyIncome : "Other",

        rentMortgage: "Monthly Rent/Mortgage",
        carPayments: "Monthly Car Payments",
        carInsurance: "Monthly Car Insurance",
        privateHealthInsurance: "Private Health Insurance",
        medicalDentalBillPayments: "Medical / Dental Bill Payments",
        alimonyChildSupportPayments: "Alimony / Child Support Payments",
        totalMonthlyCreditCardPayments: "Monthly Credit Card Payments",
        studentLoanPayments: "Student Loan Payments",
        applianceFurniturePayments: "Appliance / Furniture Payments",
        otherLoanPayments: "Other Loan Payments",

        resultsBreakdown: "Here are Your Results…",
        fieldsErrorMessage: 'Your income is lower than your expenses.',
        safeWord: 'Safe',
        okWord: 'OK',
        stressfulWord: 'Too High',
        totalIncomeText: 'Total Income',
        totalDebtText: 'Total Debt',
        debtRatioText: 'Debt Ratio',
        helpText: 'Provide at least one value per section.',
        debtText: 'Debts',
        remainingsText: 'Remaining',
        chartHelpAText: 'The less income that you spend on debt, the easier it is to maintain stability. Keeping a low DTI also helps you avoid credit card debt.',
        chartHelpBText: 'Focus on paying off debt until your DTI is below 36%. Avoid applying for loans and making new credit card charges until then.',
        chartHelpCText: 'Spending this much income on debt can make it difficult to balance your budget. You may be relying on credit to cover daily expenses.',
    },
    fr : {
        monthlyIncomeText: "Total Monthly Income",
        monthlyDebtPaymentsText: 'Total Monthly Payments',
        yourMonthlyIncome: "Your Monthly Income",
        partnerMonthlyIncome: "Partner's Monthly Income",
        alimoneyChildSupport: "Alimony / Child Support Received",
        pensionRetirementReceived: "Pension / Retirement Benefits",
        socialSecurityReceived: "Social Security Benefits",
        governmentAssistance: "Government Assistance",
        otherMonthlyIncome : "Other",

        rentMortgage: "Monthly Rent/Mortgage",
        carPayments: "Monthly Car Payments",
        carInsurance: "Monthly Car Insurance",
        privateHealthInsurance: "Private Health Insurance",
        medicalDentalBillPayments: "Medical / Dental Bill Payments",
        alimonyChildSupportPayments: "Alimony / Child Support Payments",
        totalMonthlyCreditCardPayments: "Monthly Credit Card Payments",
        studentLoanPayments: "Student Loan Payments",
        applianceFurniturePayments: "Appliance / Furniture Payments",
        otherLoanPayments: "Other Loan Payments",

        resultsBreakdown: "Here are Your Results…",
        fieldsErrorMessage: 'Your income is lower than your expenses.',
        safeWord: 'Safe',
        okWord: 'OK',
        stressfulWord: 'Too High',
        totalIncomeText: 'Total Income',
        totalDebtText: 'Total Debt',
        debtRatioText: 'Debt Ratio',
        helpText: 'Provide at least one value per section.',
        debtText: 'Debts',
        remainingsText: 'Remaining',
        chartHelpAText: 'The less income that you spend on debt, the easier it is to maintain stability. Keeping a low DTI also helps you avoid credit card debt.',
        chartHelpBText: 'Focus on paying off debt until your DTI is below 36%. Avoid applying for loans and making new credit card charges until then.',
        chartHelpCText: 'Spending this much income on debt can make it difficult to balance your budget. You may be relying on credit to cover daily expenses.',
    },

};

export default function getTranslations(lan) {
    return translations[lan];
}