const translations = {
    en : {
        monthlyIncomeText: 'Monthly Gross Income',
        monthlyIncomeTooltip: 'This is the income you make before any taxes or deductions.',
        monthlyDebtText: 'Monthly Debt Payments',
        monthlyDebtTooltip: 'This should include all debt payments, minus your existing mortgage or rent payments.',
        downPaymentText: 'Down Payment',
        downPaymentTooltip: 'Choose one of these options based on your credit score and the type of loan you plan to get.',
        loanTermText: 'Term of the Loan',
        loanTermTooltip: 'This is the amount of time you have to repay the loan.',
        anualInterestRateText: 'Annual Interest Rate',
        anualInterestRateTooltip: 'This is the APR applied to your loan; this should be estimated based on your credit score.',
        traditionaltext: 'traditional',
        lessThanText: 'less than',
        moreThanText: 'more than',
        yearsText: 'years',
        howMuchHomeCanYouAffordText: 'How Much Home Can You Afford?',
        estimatedHomePriceText: 'Estimated Home Price',
        maximumMortgageLoanAmountText: 'Maximum Mortgage Loan Amount',
        estimatedMonthlyPaymentText: 'Estimated Monthly Payment',
        viewEstimatedMonthlyPaymentSummaryText: 'View estimated monthly payment summary',
        hideExtraInformation: 'Hide Extra Information',
        estimatedMonthlyPaymentTooltip: 'Most mortgage payments include Principal, Interest, Taxes and Insurance (PITI). You can adjust estimated taxes and insurance, which will change your monthly payment.',
        principal_InterestText: 'Principal & Interest',
        estimatedTaxesAndInsuranceText: 'Estimated Taxes and Insurance',
        totalMonthlyPaymentText: 'Total monthly payment',
        monthlyIncomeError: 'Positive value between 1 and 10 million. The value should be greater than your expenses.',
        monthlyDebtError: 'Invalid number. Insert a value lower than your Gross Income.',
        anualInterestRateError: 'Invalid number. Insert a value between 0 and 7.',
        resultError: 'At this time you do not qualify for a mortgage loan due to your income and debt amounts.'
    },
    es : {
        monthlyIncomeText: 'Ingreso Total Mensual',
        monthlyIncomeTooltip: 'Es la cantidad total de sus ingresos, antes de los impuestos y otras deducciones.',
        monthlyDebtText: 'Pagos de Deuda Mensuales',
        monthlyDebtTooltip: 'Incluya todos sus pagos de deudas, menos sus pagos de hipoteca o renta.',
        downPaymentText: 'Pago Inicial',
        downPaymentTooltip: 'Elija una de estas opciones con base en su puntaje de crédito y el tipo de préstamo que va a tomar.',
        loanTermText: 'Término del Préstamo',
        loanTermTooltip: 'Es la cantidad de tiempo que usted tendrá para pagar el total del monto del préstamo.',
        anualInterestRateText: 'Tasa de Interés Anual',
        anualInterestRateTooltip: 'Es la tasa de interés anual de su préstamo, que debe ser estimada con base en su puntaje de crédito.',
        traditionaltext: 'tradicional',
        lessThanText: 'menor que',
        moreThanText: 'mayor que',
        yearsText: 'años',
        howMuchHomeCanYouAffordText: '¿Cuánto puede pagar por una casa?',
        estimatedHomePriceText: 'Precio Estimado de la Casa',
        maximumMortgageLoanAmountText: 'Cantidad Máxima del Préstamo de Hipoteca',
        estimatedMonthlyPaymentText: 'Pago Mensual Estimado',
        viewEstimatedMonthlyPaymentSummaryText: 'Ver resumen de pagos mensuales estimados',
        hideExtraInformation: 'Esconder información adicional',
        estimatedMonthlyPaymentTooltip: 'La mayoría de los pagos de hipoteca incluyen el pago del principal, intereses, impuestos y el seguro. Puede ajustar el seguro y los impuestos estimados, lo que cambiará su pago mensual.',
        principal_InterestText: 'Principal e Intereses',
        estimatedTaxesAndInsuranceText: 'Impuestos y Seguro Estimados',
        totalMonthlyPaymentText: 'Pago Mensual Total',

        monthlyIncomeError: 'Use valores positivos entre 1 y 10 millones. El valor de sus ingresos debe ser mayor que sus gastos.',
        monthlyDebtError: 'Número invalido. Inserte un valor inferior a su ingreso mensual bruto.',
        anualInterestRateError: 'Número invalido. Inserte un valor entre 0 y 7.',
        resultError: 'En este momento no califica para un préstamo hipotecario debido a sus ingresos y montos de deuda.'
    },
    ca : {
        monthlyIncomeText: 'Monthly Gross Income',
        monthlyIncomeTooltip: 'This is the income you make before any taxes or deductions.',
        monthlyDebtText: 'Monthly Debt Payments',
        monthlyDebtTooltip: 'This should include all debt payments, minus your existing mortgage or rent payments.',
        downPaymentText: 'Down Payment',
        downPaymentTooltip: 'Choose one of these options based on your credit score and the type of loan you plan to get.',
        loanTermText: 'Term of the Loan',
        loanTermTooltip: 'This is the amount of time you have to repay the loan.',
        anualInterestRateText: 'Annual Interest Rate',
        anualInterestRateTooltip: 'This is the APR applied to your loan; this should be estimated based on your credit score.',
        traditionaltext: 'traditional',
        lessThanText: 'less than',
        moreThanText: 'more than',
        yearsText: 'years',
        howMuchHomeCanYouAffordText: 'How Much Home Can You Afford?',
        estimatedHomePriceText: 'Estimated Home Price',
        maximumMortgageLoanAmountText: 'Maximum Mortgage Loan Amount',
        estimatedMonthlyPaymentText: 'Estimated Monthly Payment',
        viewEstimatedMonthlyPaymentSummaryText: 'View estimated monthly payment summary',
        hideExtraInformation: 'Hide Extra Information',
        estimatedMonthlyPaymentTooltip: 'Most mortgage payments include Principal, Interest, Taxes and Insurance (PITI). You can adjust estimated taxes and insurance, which will change your monthly payment.',
        principal_InterestText: 'Principal & Interest',
        estimatedTaxesAndInsuranceText: 'Estimated Taxes and Insurance',
        totalMonthlyPaymentText: 'Total monthly payment',
        monthlyIncomeError: 'Positive value between 1 and 10 million. The value should be greater than your expenses.',
        monthlyDebtError: 'Invalid number. Insert a value lower than your Gross Income.',
        anualInterestRateError: 'Invalid number. Insert a value between 0 and 7.',
        resultError: 'At this time you do not qualify for a mortgage loan due to your income and debt amounts.'
    },
    fr : {
        monthlyIncomeText: 'Monthly Gross Income',
        monthlyIncomeTooltip: 'This is the income you make before any taxes or deductions.',
        monthlyDebtText: 'Monthly Debt Payments',
        monthlyDebtTooltip: 'This should include all debt payments, minus your existing mortgage or rent payments.',
        downPaymentText: 'Down Payment',
        downPaymentTooltip: 'Choose one of these options based on your credit score and the type of loan you plan to get.',
        loanTermText: 'Term of the Loan',
        loanTermTooltip: 'This is the amount of time you have to repay the loan.',
        anualInterestRateText: 'Annual Interest Rate',
        anualInterestRateTooltip: 'This is the APR applied to your loan; this should be estimated based on your credit score.',
        traditionaltext: 'traditional',
        lessThanText: 'less than',
        moreThanText: 'more than',
        yearsText: 'years',
        howMuchHomeCanYouAffordText: 'How Much Home Can You Afford?',
        estimatedHomePriceText: 'Estimated Home Price',
        maximumMortgageLoanAmountText: 'Maximum Mortgage Loan Amount',
        estimatedMonthlyPaymentText: 'Estimated Monthly Payment',
        viewEstimatedMonthlyPaymentSummaryText: 'View estimated monthly payment summary',
        hideExtraInformation: 'Hide Extra Information',
        estimatedMonthlyPaymentTooltip: 'Most mortgage payments include Principal, Interest, Taxes and Insurance (PITI). You can adjust estimated taxes and insurance, which will change your monthly payment.',
        principal_InterestText: 'Principal & Interest',
        estimatedTaxesAndInsuranceText: 'Estimated Taxes and Insurance',
        totalMonthlyPaymentText: 'Total monthly payment',
        monthlyIncomeError: 'Positive value between 1 and 10 million. The value should be greater than your expenses.',
        monthlyDebtError: 'Invalid number. Insert a value lower than your Gross Income.',
        anualInterestRateError: 'Invalid number. Insert a value between 0 and 7.',
        resultError: 'At this time you do not qualify for a mortgage loan due to your income and debt amounts.'
    },

};

export default function getTranslations(lan) {
    return translations[lan];
}