const translations = {
    en : {
        sectionTitletext: 'Find out how much you could save',
        sectionSubtitletext: 'Just tell us how much you owe, in total, and we’ll estimate your new consolidated monthly payment.',
        inputDebtLabel: 'Debt Amount',
        inputDebtPlaceholder: 'Enter Amount',
        monthtext: 'month',
        perMonth: 'per month',
        monthPluralText: 'months',
        yearText: 'year',
        yearPluralText: 'years',
        debtInputError: 'Debt Amount should be greather than 0.',
        btnAriaLabel: 'Get Your Savings Results',
        btnTitle: 'See Savings',
        youCanSaveText: 'YOU CAN SAVE!',
        timePayFullText: 'Time to Pay in Full:',
        totalInterestText: 'Total Interest',
        totalCostandIntrestText: 'Total cost, including interest',
        ctaLabel: 'Get Started Today',
        callText: 'Call',
        nowText: 'now',
        dontwait1: 'Don’t want to wait to get the help you need?',
        dontwait2: 'See if you qualify and sign up without delay, so you can start getting relief today.',
        credUWText: 'Member of United Way’s Chairman’s Circle',
        withThisDebtText: 'With this amount of debt, you’d pay around',
        dmpComparisonText: 'Debt Management Program (DMP) Comparison',
        withDMPText: 'With a DMP',
        onlyMinimumPaymentsText: 'Min. Payments Only',
        timeSavedText: 'Time Saved',
        savedText: 'Saved',
        totalAmountSaved: 'Total amount saved',
        youSaveText: 'You Save',
        loadingText: 'Loading...',
        disclaimer: "* This DMP estimate compares paying your minimum credit card debt payments on your own vs. the potential benefit of using a Debt Management Plan through completion. IT’S NOT AN ACTUAL QUOTE. The DMP Estimate is based on 2.15% of your balance owed. Actual interest rates will vary by consumer and creditor – yours could be higher or lower. Consolidated Credit might be able to reduce your interest rates and late fees allowing you to pay off your credit card debt quicker (since more payments are applied to your principal balances, saving you lots of money in the long run). To complete the program, you must make on-time payments each month. Late or missed payments may cause your program to be canceled and in that event, this estimate would not apply to you.",
    },
    es : {
        sectionTitletext: 'Vea cuánto más usted puede ahorrar',
        sectionSubtitletext: 'Díganos cuánto es el monto total de sus deudas, y nosotros le prepararemos un estimado de cuánto serán sus pagos si consolida sus deudas.',
        inputDebtLabel: 'Deuda',
        inputDebtPlaceholder: 'Entre su Deuda',
        monthtext: 'mes',
        perMonth: 'por mes',
        monthPluralText: 'meses',
        yearText: 'año',
        yearPluralText: 'años',
        debtInputError: 'El valor de su deuda debe ser mayor que 0.',
        btnAriaLabel: 'Obtenga los resultados de ahorro',
        btnTitle: 'Calcular Ahorros',
        youCanSaveText: 'USTED PUEDE AHORRAR!',
        timePayFullText: 'Tiempo para Pagar:',
        totalInterestText: 'Total de Intereses',
        totalCostandIntrestText: 'Costo total con intereses incluidos',
        ctaLabel: 'Comience Hoy',
        callText: 'LLámanos',
        nowText: 'hoy',
        dontwait1: '¿No quieres esperar para obtener la ayuda que necesitas?',
        dontwait2: 'Vea si califica e inscríbase sin demora para que pueda comenzar a recibir alivio de su deuda hoy.',
        credUWText: 'Miembro del Círculo del Presidente de United Way',
        credBBBText: 'Consolidted Credit tiene una calificación A+ con el Better Business Bureau',
        withThisDebtText: 'Con esta cantidad de ahorro, ud. deberá pagar alrededor de',
        dmpComparisonText: 'Comparación del Programa de Manejo de Deudas (DMP)',
        withDMPText: 'Con el Programa (DMP)',
        onlyMinimumPaymentsText: 'Pagos Mínimos Solamente',
        timeSavedText: 'Tiempo Ahorrado',
        savedText: 'Ahorrados',
        totalAmountSaved: 'Cantidad total ahorrado',
        youSaveText: 'Ud. Ahorra',
        loadingText: 'Cargando...',
        disclaimer: "* Este cálculo compara el pago de su deuda de tarjeta de crédito por su cuenta frente al beneficio potencial de utilizar un Plan de gestión de deuda hasta su finalización. NO ES UNA CITA REAL. La estimación se basa en el 2.15% de su saldo adeudado. Las tasas de interés reales variarán según el consumidor y el acreedor; el suyo podría ser mayor o menor. Consolidated Credit podría reducir sus tasas de interés y cargos por pagos atrasados, lo que le permite cancelar su deuda de tarjeta de crédito más rápidamente (ya que se aplican más pagos a sus saldos de principal, lo que le ahorra mucho dinero a largo plazo). Para completar el programa, debe hacer pagos puntuales cada mes. Los pagos atrasados o perdidos pueden causar que su programa sea cancelado y en ese caso, este estimado no se aplica a usted.",
    },
    ca : {
        sectionTitletext: 'Find out how much you could save',
        sectionSubtitletext: 'Just tell us how much you owe, in total, and we’ll estimate your new consolidated monthly payment.',
        inputDebtLabel: 'Debt Amount',
        inputDebtPlaceholder: 'Enter Amount',
        monthtext: 'month',
        perMonth: 'per month',
        monthPluralText: 'months',
        yearText: 'year',
        yearPluralText: 'years',
        debtInputError: 'Debt Amount should be greather than 0.',
        btnAriaLabel: 'Get Your Savings Results',
        btnTitle: 'See Savings',
        youCanSaveText: 'YOU CAN SAVE!',
        timePayFullText: 'Time to Pay in Full:',
        totalInterestText: 'Total Interest',
        totalCostandIntrestText: 'Total cost, including interest',
        ctaLabel: 'Get Started Today',
        callText: 'Call',
        nowText: 'now',
        dontwait1: 'Don’t want to wait to get the help you need?',
        dontwait2: 'See if you qualify and sign up without delay, so you can start getting relief today.',
        credUWText: 'Member of United Way’s Chairman’s Circle',
        credBBBText: 'Consolidated Credit Carries an A+ rating by the Better Business Bureau',
        withThisDebtText: 'With this amount of debt, you’d pay around',
        dmpComparisonText: 'Debt Management Program (DMP) Comparison',
        withDMPText: 'With a DMP',
        onlyMinimumPaymentsText: 'Min. Payments Only',
        timeSavedText: 'Time Saved',
        savedText: 'Saved',
        totalAmountSaved: 'Total amount saved',
        youSaveText: 'You Save',
        loadingText: 'Loading...',
        disclaimer: "* This DMP estimate compares paying your minimum credit card debt payments on your own vs. the potential benefit of using a Debt Management Plan through completion. IT’S NOT AN ACTUAL QUOTE. The DMP Estimate is based on 2.50% of your balance owed. Actual interest rates will vary by consumer and creditor – yours could be higher or lower. Consolidated Credit might be able to reduce your interest rates and late fees allowing you to pay off your credit card debt quicker (since more payments are applied to your principal balances, saving you lots of money in the long run). To complete the program, you must make on-time payments each month. Late or missed payments may cause your program to be cancelled and in that event, this estimate would not apply to you.",
    },
    fr : {
        sectionTitletext: 'Find out how much you could save',
        sectionSubtitletext: 'Just tell us how much you owe, in total, and we’ll estimate your new consolidated monthly payment.',
        inputDebtLabel: 'Debt Amount',
        inputDebtPlaceholder: 'Enter Amount',
        monthtext: 'Month',
        perMonth: 'per month',
        monthPluralText: 'months',
        yearText: 'year',
        yearPluralText: 'years',
        debtInputError: 'Debt Amount should be greather than 0.',
        btnAriaLabel: 'Get Your Savings Results',
        btnTitle: 'See Savings',
        youCanSaveText: 'YOU CAN SAVE!',
        timePayFullText: 'Time to Pay in Full:',
        totalInterestText: 'Total Interest',
        totalCostandIntrestText: 'Total cost, including interest',
        ctaLabel: 'Get Started Today',
        callText: 'Call',
        nowText: 'now',
        dontwait1: 'Don’t want to wait to get the help you need?',
        dontwait2: 'See if you qualify and sign up without delay so you can start getting relief today.',
        credUWText: 'Member of United Way’s Chairman’s Circle',
        credBBBText: 'Consolidated Credit Carries an A+ rating by the Better Business Bureau',
        withThisDebtText: 'With this amount of debt, you’d pay around',
        dmpComparisonText: 'Debt Management Program (DMP) Comparison',
        withDMPText: 'With A DMP',
        onlyMinimumPaymentsText: 'Min. Payments Only',
        timeSavedText: 'Time Saved',
        savedText: 'Saved',
        totalAmountSaved: 'Total amount saved',
        youSaveText: 'You Save',
        loadingText: 'Loading...',
        disclaimer: "* This DMP estimate compares paying your minimum credit card debt payments on your own vs. the potential benefit of using a Debt Management Plan through completion. IT’S NOT AN ACTUAL QUOTE. The DMP Estimate is based on 2.50% of your balance owed. Actual interest rates will vary by consumer and creditor – yours could be higher or lower. Consolidated Credit might be able to reduce your interest rates and late fees allowing you to pay off your credit card debt quicker (since more payments are applied to your principal balances, saving you lots of money in the long run). To complete the program, you must make on-time payments each month. Late or missed payments may cause your program to be cancelled and in that event, this estimate would not apply to you.",
    }

};

export default function getTranslations(lan) {
    return translations[lan];
}