const translations = {
    en : {
        monthtext: 'Months',
        monthSingularText: 'month',
        monthPluralText: 'months',
        yearText: 'year',
        month : ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'],
        principalText: 'Principle',
        interestText: 'Interest',
        minimumPaymentText: 'Minimum Payment',
        principalPaidText: 'Principle Paid',
        interestPaidText: 'Interest Paid',
        remainingBalanceText: 'Remaining Balance',
        totalInterestText: 'Total Interest',
        calculateText: 'Calculate',
        currentBalanceLabel : 'What is your credit card balance?',
        currentBalanceTooltip: 'Enter the current balance from each of your credit cards one at a time. You can find the current balance on your most recent credit card statement.',
        aprLabel: 'APR (annual percentage rate)',
        aprTooltip: 'Enter the current APR for purchases from that card; this information will also be listed on your most current credit card statement.',
        minimumPaymentLabel1: 'How is your minimum payment calculated?',
        balancePercentageLabel: 'Percentage of Balance',
        balancePercentageTooltip: 'Minimum payment requirements are calculated as a percentage of what you owe. The calculation should be listed on your original credit card agreement or you can simply use the default option of 3%, which is standard for most cards.',
        balancePercentageOptionOne: 'Interest + 1% of balance',
        minimumPaymentLabel2: 'Next Minimum Payment is',
        minimumPaymentTooltip: 'Minimum payments increase or decrease based on your balance. So, as you pay off credit card balances, the minimum payment requirement will gradually decrease over time.',
        debtFreeByText: 'You’ll be debt-free by',
        totalAmountText: 'Total amount you’ll pay (including interest)',
        tableResultsTitle: 'Payment Schedule',
        requiredFieldError: 'This field is required.',
        balanceFieldError: 'Insert a number between 1 and 1 million.',
        balanceHelpText: 'Numeric values only, dots and commas will be removed.',
        orText: 'or',
        paymentText: 'payments',
        andText: 'and',
        noteText: 'NOTE',
        apiErrorText1: 'If you make payments equal or under ',
        apiErrorText2: ', you will never be able to pay your debt. Please change the values ​on the form to obtain a higher minimum payment.',
        cautionText: 'CAUTION',
        disclaimerText: 'Federal regulations require credit card issuers to disclose on your credit card statement how long it will take to pay off your estimated balance if you make minimum monthly payments. Estimates may be rounded up to the next $100. This debt calculator uses your actual credit card balance, so the results may vary from the estimate shown in your credit card statement.',
        disclaimerText2: '* This estimate compares paying your credit card debt on your own vs. the potential benefit of using a Debt Management Plan through completion. IT\'S NOT AN ACTUAL QUOTE. Estimate is based on 2.15% of your balance owed. Actual interest rates will vary by consumer and creditor – yours could be higher or lower. Consolidated Credit might be able to reduce your interest rates and late fees allowing you to pay off your credit card debt quicker (since more payments are applied to your principle balances, saving you lots of money in the long run). To complete the program, you must make on-time payments each month. Late or missed payments may cause your program to be cancelled and in that event, this estimate would not apply to you.',
        loadingText: 'Loading...',
        goToPaymentScheduleText: 'Show Payment Schedule',
        paymentTypeLabel: 'Select a payment schedule based on:',
        paymentTypeLabelTooltip: 'This is a set amount of money you are willing to spend each month to pay off your credit card, regardless of the amount owed. It must be greater than or equal to your first minimum monthly payment.',
        paymentTypeMinim: 'Minimum payment',
        paymentTypeFixed: 'Fixed payment',
        fixedPaymentLabel: 'Fixed monthly payment:',
        fixedPaymentDisclaimer: '*Your fixed payment must be greater than or equal to your first minimum monthly payment and no grater than $10000*',
        resultsMinimumPaymentHeader: "With a minimum payment",
        resultsFixedPaymentHeader: 'With a fixed payment:',
        resultsFixedPaymentContent: 'It will take you ##term## to be rid of your debt. In that time, you will pay: ##amount## in interest',
    },
    es : {
        monthtext: 'Meses',
        monthSingularText: 'mes',
        monthPluralText: 'meses',
        yearText: 'año',
        month : ['Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio', 'Julio', 'Agosto', 'Septiembre', 'Octuber', 'Noviembre', 'Diciembre'],
        principalText: 'Principle',
        interestText: 'Intereses',
        minimumPaymentText: 'Pago Mínimo',
        principalPaidText: 'Capital Pagado',
        interestPaidText: 'Intereses Pagados',
        remainingBalanceText: 'Balance Restante',
        totalInterestText: 'Interés Total',
        calculateText: 'Calcular',
        currentBalanceLabel : '¿Cuál es el saldo de su tarjeta de crédito?',
        currentBalanceTooltip: 'Esta es la cantidad total que se debe actualmente en su tarjeta de crédito. Esto se puede encontrar en el estado de cuenta de su tarjeta de crédito más reciente.',
        aprLabel: 'APR (tasa de porcentaje anual) ',
        aprTooltip: 'Esta es la Tasa de Interés Anual que paga en su tarjeta de crédito. Esto se puede encontrar en el estado de cuenta de su tarjeta de crédito.',
        minimumPaymentLabel1: '¿Cómo será calculado su pago mínimo?',
        balancePercentageLabel: 'Porcentaje de saldo',
        balancePercentageTooltip: 'El cálculo del pago mínimo mensual es el porcentaje o la fórmula utilizada para determinar el pago mínimo solicitado en su factura de tarjeta de crédito cada mes. Este cálculo debe especificarse en su contrato de Acuerdo de Tarjeta de Crédito y / o en su estado de cuenta de tarjeta de crédito.',
        balancePercentageOptionOne: 'Interés + el 1% del balance',
        minimumPaymentLabel2: 'El próximo pago mínimo es',
        minimumPaymentTooltip: 'Los pagos mínimos aumentan o disminuyen en función de su saldo. Por lo tanto, a medida que paga los saldos de las tarjetas de crédito, el requisito de pago mínimo disminuirá gradualmente con el tiempo.',
        debtFreeByText: 'Estarás libre de deudas en',
        totalAmountText: 'Cantidad total que pagará (incluidos los intereses)',
        tableResultsTitle: 'Calendario de Pagos',
        requiredFieldError: 'Este campo es requerido.',
        balanceFieldError: 'Inserte un número mayor que 0 y menor que 1 millón.',
        balanceHelpText: 'Los puntos y las comas serán eliminados',
        orText: 'o',
        paymentText: 'pagos',
        andText: 'y',
        noteText: 'NOTA',
        apiErrorText1: 'Si realiza pagos menores que ',
        apiErrorText2: ', nunca podrá pagar su deuda. Para obtener un Pago Mínimo más alto, debe cambiar los valores en el formulario.',
        cautionText: 'ADVERTENCIA',
        disclaimerText: 'Las regulaciones federales requieren que los emisores de tarjetas de crédito divulguen en su estado de cuenta de la tarjeta de crédito cuanto tiempo tomará para pagar su saldo estimado si hace los pagos mensuales mínimos. Las estimaciones se pueden redondear hasta los próximos $100. Esta calculadora de deudas usa su balance de tarjeta de crédito actual, así que los resultados pueden variar de los estimados mostrados en su estado de cuenta de tarjeta de crédito.',
        disclaimerText2: '* Este cálculo compara el pago de su deuda de tarjeta de crédito por su cuenta frente al beneficio potencial de utilizar un Plan de gestión de deuda hasta su finalización. NO ES UNA CITA REAL. La estimación se basa en el 2.15% de su saldo adeudado. Las tasas de interés reales variarán según el consumidor y el acreedor; el suyo podría ser mayor o menor. Consolidated Credit podría reducir sus tasas de interés y cargos por pagos atrasados, lo que le permite cancelar su deuda de tarjeta de crédito más rápidamente (ya que se aplican más pagos a sus saldos de principle, lo que le ahorra mucho dinero a largo plazo). Para completar el programa, debe hacer pagos puntuales cada mes. Los pagos atrasados o perdidos pueden causar que su programa sea cancelado y en ese caso, este estimado no se aplica a usted.',
        loadingText: 'Cargando...',
        goToPaymentScheduleText: 'Vea el Calendario de Pagos',
        paymentTypeLabel: 'Seleccione un calendario de pagos basado en:',
        paymentTypeLabelTooltip: 'Esta es una cantidad fija de dinero que está dispuesto a gastar cada mes para pagar su tarjeta de crédito, independientemente de la cantidad que se debe. Debe ser mayor o igual que su primer pago mensual mínimo.',
        paymentTypeMinim: 'Pago mínimo solamente',
        paymentTypeFixed: 'Pagos fijos',
        fixedPaymentLabel: 'Primer pago mensual:',
        fixedPaymentDisclaimer: '*Su pago mensual fijo debe de ser mayor o igual a su primer pago mensual mínimo y mayor de $10000*',
        resultsMinimumPaymentHeader: "Con un pago mínimo",
        resultsFixedPaymentHeader: 'Con un pago fijo de:',
        resultsFixedPaymentContent: 'Le llevará ##term## deshacerse de su deuda. En ese tiempo, Ud. pagará: ##amount## En intereses.',
    },
    ca : {
        monthtext: 'Months',
        monthSingularText: 'month',
        monthPluralText: 'months',
        yearText: 'year',
        month : ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'],
        principalText: 'Principle',
        interestText: 'Interest',
        minimumPaymentText: 'Minimum Payment',
        principalPaidText: 'Principle Paid',
        interestPaidText: 'Interest Paid',
        remainingBalanceText: 'Remaining Balance',
        totalInterestText: 'Total Interest',
        calculateText: 'Calculate',
        currentBalanceLabel : 'What is your credit card balance?',
        currentBalanceTooltip: 'Enter the current balance from each of your credit cards one at a time. You can find the current balance on your most recent credit card statement.',
        aprLabel: 'APR (annual percentage rate)',
        aprTooltip: 'Enter the current APR for purchases from that card; this information will also be listed on your most current credit card statement.',
        minimumPaymentLabel1: 'How is your minimum payment calculated?',
        balancePercentageLabel: 'Percentage of Balance',
        balancePercentageTooltip: 'Minimum payment requirements are calculated as a percentage of what you owe. The calculation should be listed on your original credit card agreement or you can simply use the default option of 3%, which is standard for most cards.',
        balancePercentageOptionOne: 'Interest + 1% of balance',
        minimumPaymentLabel2: 'Next Minimum Payment is',
        minimumPaymentTooltip: 'Minimum payments increase or decrease based on your balance. So, as you pay off credit card balances, the minimum payment requirement will gradually decrease over time.',
        debtFreeByText: 'You’ll be debt-free by',
        totalAmountText: 'Total amount you’ll pay (including interest)',
        tableResultsTitle: 'Payment Schedule',
        requiredFieldError: 'This field is required.',
        balanceFieldError: 'Insert a number between 1 and 1 million.',
        balanceHelpText: 'Dots and commas will be removed.',
        orText: 'or',
        paymentText: 'payments',
        andText: 'and',
        noteText: 'NOTE',
        apiErrorText1: 'If you make payments equal or under ',
        apiErrorText2: ', you will never be able to pay your debt. Please change the values ​on the form to obtain a higher minimum payment.',
        cautionText: 'CAUTION',
        disclaimerText: 'Federal regulations require credit card issuers to disclose on your credit card statement how long it will take to pay off your estimated balance if you make minimum monthly payments. Estimates may be rounded up to the next $100. This debt calculator uses your actual credit card balance, so the results may vary from the estimate shown in your credit card statement.',
        disclaimerText2: '* This estimate compares paying your credit card debt on your own vs. the potential benefit of using a Debt Management Plan through completion. IT\'S NOT AN ACTUAL QUOTE. Estimate is based on 2.5% of your balance owed. Actual interest rates will vary by consumer and creditor – yours could be higher or lower. Consolidated Credit might be able to reduce your interest rates and late fees allowing you to pay off your credit card debt quicker (since more payments are applied to your principle balances, saving you lots of money in the long run). To complete the program, you must make on-time payments each month. Late or missed payments may cause your program to be cancelled and in that event, this estimate would not apply to you.',
        loadingText: 'Loading...',
        goToPaymentScheduleText: 'Show Payment Schedule',
        paymentTypeLabel: 'Select a payment schedule based on:',
        paymentTypeLabelTooltip: 'This is a set amount of money you are willing to spend each month to pay off your credit card, regardless of the amount owed. It must be greater than or equal to your first minimum monthly payment.',
        paymentTypeMinim: 'Minimum payment',
        paymentTypeFixed: 'Fixed payment',
        fixedPaymentLabel: 'Fixed monthly payment:',
        fixedPaymentDisclaimer: '*Your fixed payment must be greater than or equal to your first minimum monthly payment and no grater than $10000*',
        resultsMinimumPaymentHeader: "With a minimum payment",
        resultsFixedPaymentHeader: 'With a fixed payment:',
        resultsFixedPaymentContent: 'It will take you ##term## to be rid of your debt. In that time, you will pay: ##amount## in interest',
    },
    fr : {
        monthtext: 'Months',
        monthSingularText: 'month',
        monthPluralText: 'months',
        yearText: 'year',
        month : ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'],
        principalText: 'Principle',
        interestText: 'Interest',
        minimumPaymentText: 'Minimum Payment',
        principalPaidText: 'Principle Paid',
        interestPaidText: 'Interest Paid',
        remainingBalanceText: 'Remaining Balance',
        totalInterestText: 'Total Interest',
        calculateText: 'Calculate',
        currentBalanceLabel : 'What is your credit card balance?',
        currentBalanceTooltip: 'Enter the current balance from each of your credit cards one at a time. You can find the current balance on your most recent credit card statement.',
        aprLabel: 'APR (annual percentage rate)',
        aprTooltip: 'Enter the current APR for purchases from that card; this information will also be listed on your most current credit card statement.',
        minimumPaymentLabel1: 'How is your minimum payment calculated?',
        balancePercentageLabel: 'Percentage of Balance',
        balancePercentageTooltip: 'Minimum payment requirements are calculated as a percentage of what you owe. The calculation should be listed on your original credit card agreement or you can simply use the default option of 3%, which is standard for most cards.',
        balancePercentageOptionOne: 'Intérêts + 1% du solde',
        minimumPaymentLabel2: 'Next Minimum Payment is',
        minimumPaymentTooltip: 'Minimum payments increase or decrease based on your balance. So, as you pay off credit card balances, the minimum payment requirement will gradually decrease over time.',
        debtFreeByText: 'You’ll be debt-free by',
        totalAmountText: 'Total amount you’ll pay (including interest)',
        tableResultsTitle: 'Payment Schedule',
        requiredFieldError: 'This field is required.',
        balanceFieldError: 'This field is required and must be a number greater than 0',
        balanceHelpText: 'Dots and commas will be removed.',
        orText: 'or',
        paymentText: 'payments',
        andText: 'and',
        noteText: 'NOTE',
        apiErrorText1: 'If you make payments equal or under ',
        apiErrorText2: ', you will never be able to pay your debt. Please change the values ​on the form to obtain a higher minimum payment.',
        cautionText: 'CAUTION',
        disclaimerText: 'Federal regulations require credit card issuers to disclose on your credit card statement how long it will take to pay off your estimated balance if you make minimum monthly payments. Estimates may be rounded up to the next $100. This debt calculator uses your actual credit card balance, so the results may vary from the estimate shown in your credit card statement.',
        disclaimerText2: '* This estimate compares paying your credit card debt on your own vs. the potential benefit of using a Debt Management Plan through completion. IT\'S NOT AN ACTUAL QUOTE. Estimate is based on 2.5% of your balance owed. Actual interest rates will vary by consumer and creditor – yours could be higher or lower. Consolidated Credit might be able to reduce your interest rates and late fees allowing you to pay off your credit card debt quicker (since more payments are applied to your principle balances, saving you lots of money in the long run). To complete the program, you must make on-time payments each month. Late or missed payments may cause your program to be cancelled and in that event, this estimate would not apply to you.',
        loadingText: 'Loading...',
        goToPaymentScheduleText: 'Show Payment Schedule',
        paymentTypeLabel: 'Select a payment schedule based on:',
        paymentTypeLabelTooltip: 'This is a set amount of money you are willing to spend each month to pay off your credit card, regardless of the amount owed. It must be greater than or equal to your first minimum monthly payment.',
        paymentTypeMinim: 'Minimum payment',
        paymentTypeFixed: 'Fixed payment',
        fixedPaymentLabel: 'Fixed monthly payment:',
        fixedPaymentDisclaimer: '*Your fixed payment must be greater than or equal to your first minimum monthly payment and no grater than $10000*',
        resultsMinimumPaymentHeader: "Avec un paiement minimum",
        resultsFixedPaymentHeader: 'With a fixed payment:',
        resultsFixedPaymentContent: 'It will take you ##term## to be rid of your debt. In that time, you will pay: ##amount## in interest',
    },

};

export default function getTranslations(lan) {
    return translations[lan];
}
